<?php
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Webserv CGI Test Page</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            background-color: #f0f2f5;
            color: #1c1e21;
            margin: 0;
            padding: 2rem;
        }
        .container {
            max-width: 800px;
            margin: auto;
            background-color: #ffffff;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            padding: 2rem;
        }
        h1, h2 {
            color: #1877f2;
            border-bottom: 2px solid #e7f3ff;
            padding-bottom: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
            word-break: break-all;
        }
        th {
            background-color: #e7f3ff;
            font-weight: 600;
        }
        tr:nth-child(even) {
            background-color: #f7f8fa;
        }
        .card {
            background-color: #f7f8fa;
            border: 1px solid #ddd;
            border-radius: 8px;
            padding: 1.5rem;
            margin-top: 2rem;
        }
        .card h2 {
            margin-top: 0;
            border: none;
        }
        input[type="text"], textarea {
            width: 100%;
            padding: 10px;
            margin-top: 5px;
            border-radius: 6px;
            border: 1px solid #ddd;
            box-sizing: border-box;
        }
        input[type="submit"] {
            background-color: #1877f2;
            color: white;
            padding: 12px 20px;
            border: none;
            border-radius: 6px;
            cursor: pointer;
            margin-top: 10px;
            font-size: 16px;
        }
        input[type="submit"]:hover {
            background-color: #166fe5;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>🚀 Webserv CGI Test Page 🚀</h1>
        <p>This page is generated by a PHP script running on your C++ webserver. Current server time is: <strong><?php echo date('Y-m-d H:i:s'); ?></strong></p>

        <h2>CGI Environment Variables (from $_SERVER)</h2>
        <table>
            <tr>
                <th>Variable Name</th>
                <th>Value</th>
            </tr>
            <?php
            foreach ($_SERVER as $key => $value) {
                echo "<tr><td>" . htmlspecialchars($key) . "</td><td>" . htmlspecialchars($value) . "</td></tr>";
            }
            ?>
        </table>

        <div class="card">
            <h2>GET Data (Query String)</h2>
            <?php
            if (!empty($_GET)) {
                echo "<table><tr><th>Key</th><th>Value</th></tr>";
                foreach ($_GET as $key => $value) {
                    echo "<tr><td>" . htmlspecialchars($key) . "</td><td>" . htmlspecialchars($value) . "</td></tr>";
                }
                echo "</table>";
            } else {
                echo "<p>No GET data was provided in the query string.</p>";
            }
            ?>
        </div>

        <div class="card">
            <h2>POST Data</h2>
            <?php
            if (!empty($_POST)) {
                echo "<table><tr><th>Key</th><th>Value</th></tr>";
                foreach ($_POST as $key => $value) {
                    echo "<tr><td>" . htmlspecialchars($key) . "</td><td>" . htmlspecialchars($value) . "</td></tr>";
                }
                echo "</table>";
            } else {
                echo "<p>No POST data was submitted. Use the form below to test.</p>";
            }
            ?>
        </div>

        <div class="card">
            <h2>Test POST Requests</h2>
            <form action="<?php echo htmlspecialchars($_SERVER["SCRIPT_NAME"]); ?>" method="post">
                <label for="name">Name:</label><br>
                <input type="text" id="name" name="name" value="Ada Lovelace"><br><br>
                <label for="message">Message:</label><br>
                <textarea id="message" name="message" rows="4">Hello from the browser!</textarea><br>
                <input type="submit" value="Submit POST Request">
            </form>
        </div>
    </div>
</body>
</html>
