#!/usr/bin/python3

import os
import sys
import cgi
from datetime import datetime

# The 'cgi' module helps in parsing QUERY_STRING and POST data
form = cgi.FieldStorage()

# --- Print HTTP headers ---
# The blank line at the end is mandatory
print("Content-Type: text/html;charset=utf-8")
print()

# --- Start HTML content ---
print("""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Webserv Python CGI Test</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background-color: #f0f2f5; color: #1c1e21; margin: 0; padding: 2rem; }
        .container { max-width: 800px; margin: auto; background-color: #ffffff; border-radius: 8px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); padding: 2rem; }
        h1, h2 { color: #27ae60; border-bottom: 2px solid #e8f6ef; padding-bottom: 10px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; word-break: break-all; }
        th { background-color: #e8f6ef; font-weight: 600; }
        tr:nth-child(even) { background-color: #f7f8fa; }
        .card { background-color: #f7f8fa; border: 1px solid #ddd; border-radius: 8px; padding: 1.5rem; margin-top: 2rem; }
        .card h2 { margin-top: 0; border: none; }
        input[type="text"], textarea { width: 100%; padding: 10px; margin-top: 5px; border-radius: 6px; border: 1px solid #ddd; box-sizing: border-box; }
        input[type="submit"] { background-color: #27ae60; color: white; padding: 12px 20px; border: none; border-radius: 6px; cursor: pointer; margin-top: 10px; font-size: 16px; }
        input[type="submit"]:hover { background-color: #229954; }
    </style>
</head>
<body>
    <div class="container">
""")

# --- Page Header ---
print("<h1>🐍 Webserv Python CGI Test 🐍</h1>")
print(f"<p>This page is generated by a Python script. Current server time is: <strong>{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</strong></p>")


# --- Display Form Data (GET and POST) ---
print('<div class="card"><h2>Submitted Data (GET & POST)</h2>')
if not form.keys():
    print("<p>No GET or POST data was submitted.</p>")
else:
    print("<table><tr><th>Key</th><th>Value</th></tr>")
    for key in form.keys():
        # Use html.escape in Python 3.8+ for better security
        value = cgi.escape(form.getvalue(key))
        print(f"<tr><td>{cgi.escape(key)}</td><td>{value}</td></tr>")
    print("</table>")
print('</div>')


# --- Display Environment Variables ---
print('<h2>CGI Environment Variables</h2>')
print("<table><tr><th>Variable Name</th><th>Value</th></tr>")
for key, value in sorted(os.environ.items()):
    print(f"<tr><td>{cgi.escape(key)}</td><td>{cgi.escape(value)}</td></tr>")
print("</table>")


# --- POST Test Form ---
script_name = os.environ.get("SCRIPT_NAME", "")
print(f"""
<div class="card">
    <h2>Test POST Requests</h2>
    <form action="{script_name}" method="post">
        <label for="py_name">Name:</label><br>
        <input type="text" id="py_name" name="py_name" value="Guido van Rossum"><br><br>
        <label for="py_message">Message:</label><br>
        <textarea id="py_message" name="py_message" rows="4">Python is running on Webserv!</textarea><br>
        <input type="submit" value="Submit POST Request">
    </form>
</div>
""")


# --- End HTML content ---
print("""
    </div>
</body>
</html>
""")

