#!/usr/bin/env python3
import os

print("Content-Type: text/html\r\n\r\n")
print("<!DOCTYPE html>")
print("<html lang='en'>")
print("<head>")
print("<meta charset='UTF-8'>")
print("<title>🐍 CGI Marker Test</title>")
print("<style>")
print("body {")
print("  margin: 0; padding: 0;")
print("  height: 100vh;")
print("  display: flex;")
print("  justify-content: center;")
print("  align-items: center;")
print("  background: radial-gradient(circle at top, #1d2b64, #f8cdda);")
print("  font-family: 'Segoe UI', sans-serif;")
print("  color: #fff;")
print("}")
print(".card {")
print("  background: rgba(0, 0, 0, 0.6);")
print("  padding: 2rem 3rem;")
print("  border-radius: 20px;")
print("  text-align: center;")
print("  box-shadow: 0 8px 25px rgba(0,0,0,0.4);")
print("  max-width: 700px;")
print("}")
print("h1 { font-size: 2rem; margin-bottom: 1.5rem; letter-spacing: 1px; }")
print(".success { color: #00ffcc; }")
print(".error { color: #ff6b6b; }")
print("pre {")
print("  background: #111;")
print("  color: #0f0;")
print("  padding: 1rem;")
print("  border-radius: 12px;")
print("  text-align: left;")
print("  white-space: pre-wrap;")
print("  font-size: 1rem;")
print("}")
print("</style>")
print("</head>")
print("<body>")
print("<div class='card'>")
print("<h1>🐍 CGI Marker Test</h1>")

test_file = "test.txt"

if os.path.exists(test_file):
    with open(test_file, "r") as f:
        content = f.read()
    print("<p class='success'>✅ marker.txt found!</p>")
    print("<pre>" + content + "</pre>")
else:
    print("<p class='error'>❌ marker.txt not found. CGI not running in the expected directory..</p>")

print("</div>")
print("</body>")
print("</html>")
